### ISSUE TITLE
how to test on my own images

### ISSUE THREAD

**Issue by Eutenacity** [Thinklab-SJTU/PCA-GM#7]
I  try to code a demo to test  the model in my own images.But i meet some problems

Can you give us the trained model params

I am confused by how to enable raw images ready to be put into the model 

I find that the keypoint coordinate is operated like (x-xmin)/w*obj_resize[0]  in the file data/pascal_voc.py.But why it need to subtract xmin

**Comment by rogerwwww** [comment]
Hi there,

Thank you for your advice on trained models. We will consider that. BTW if you train by using the configuration provided in this repo you shall get similar results.

Keypoint coordinates are minus by xmin because in Pascal VOC Keypoint instances are cropped from the original image by the bounding box.

**Comment by Eutenacity** [comment]
thanks,then I check the pascal_voc.py,finding that I comment a line that crop the instance from the original image for the sake of the fact that my PLT version does not match that line.

**Comment by rogerwwww** [comment]
If the majority of your images are occupied by the instance to be matched, it shall be fine to omit the cropping step. You may see our treatment to Willow ObjectClass, where the instances are not cropped.
